"""Removed recording url

Revision ID: 1d6ebaa88ae1
Revises: 42738e56fc72
Create Date: 2025-11-01 16:48:21.643475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6ebaa88ae1'
down_revision: Union[str, None] = '42738e56fc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'recording_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('recording_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
