"""Add answered_by column to calls table

Revision ID: 5b7b7b9b4b49
Revises: add_performance_indexes_001
Create Date: 2025-11-06 13:21:37.721168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7b7b9b4b49'
down_revision: Union[str, None] = 'add_performance_indexes_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('answered_by', sa.Enum('human', 'voicemail', 'unknown', 'no_answer', name='answered_by_enum', native_enum=False), nullable=True))
    op.create_index(op.f('ix_calls_answered_by'), 'calls', ['answered_by'], unique=False)
    op.add_column('insights', sa.Column('anomaly_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_insights_anomaly_score'), 'insights', ['anomaly_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_anomaly_score'), table_name='insights')
    op.drop_column('insights', 'anomaly_score')
    op.drop_index(op.f('ix_calls_answered_by'), table_name='calls')
    op.drop_column('calls', 'answered_by')
    # ### end Alembic commands ###
