"""add api_key_index to calls

Revision ID: aaf4a7bf2149
Revises: 5b7b7b9b4b49
Create Date: 2025-11-07 12:56:40.404082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf4a7bf2149'
down_revision: Union[str, None] = '5b7b7b9b4b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('api_key_index', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'api_key_index')
    # ### end Alembic commands ###
