"""added high revenue quote

Revision ID: ac30e721d854
Revises: 1d6ebaa88ae1
Create Date: 2025-11-01 17:51:55.735503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac30e721d854'
down_revision: Union[str, None] = '1d6ebaa88ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('revenue_interest_quote', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insights', 'revenue_interest_quote')
    # ### end Alembic commands ###
