"""added rating

Revision ID: d50412f72c75
Revises: e2537ca37501
Create Date: 2025-11-02 23:12:59.393853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50412f72c75'
down_revision: Union[str, None] = 'e2537ca37501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insights', sa.Column('gym_rating', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_insights_gym_rating'), 'insights', ['gym_rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_gym_rating'), table_name='insights')
    op.drop_column('insights', 'gym_rating')
    # ### end Alembic commands ###
